baseURL: 'https://blog.simonszu.de'
languageCode: 'de-de'
title: 'Yelling at clouds'
author: Simon Szustkowski
enableRobotsTXT: true

theme: 'hugo-flex'

permalinks:
  posts: '/:filename/'
  pages: '/:filename/'

params:
  color: chocolate
  summaries: true
  description: Simons blog
  footer: >-
    &#32;<small>Except where otherwise noted, content on this site is licensed under a &#32;
    <a href="http://creativecommons.org/licenses/by/4.0/" rel="license">Creative
    Commons Attribution 4.0 International License</a>.&#32;</small>
  divider: '\2015\2015' # Set to false to remove divider below posts on homepage
  css:
    - css/custom.css

menu:
  nav:
    - name: Home
      url: https://www.simonszu.de/
      weight: 1